### ISSUE TITLE
Docs request

### ISSUE THREAD

**Issue by nonzod** [hooyah/SevenSegments#1]
Could you provide more information related to AVR programming?

**Comment by hooyah** [comment]
I'm using Atmel studio 7 to compile the code for the Atmega328P (also works for the 328PB but that's a completely different beast).
There shouldn't be any external dependencies so it should just compile as is.
I am then using an AVRDragon USB programmer to connect to the ICSP port on the board while providing 5V power to it. (An Arduino can also be used as a programmer, ArduinoISP).
First I make sure the connection is sound and the clock is running by reading the device ID. Then I set the fuses
//	.low = 0xFF,
//	.high = 0xD9,
//	.extended = 0xFF,
and last I upload the compiled elf file.
Pretty straight forward.
